Exception handling to deal with single quotes
Under both Python 2.7.14 and 3.6.3, a single quote in an Abaco MSG causse `get_context` to fail because the AST can't decide just _how literally_ the string being passed in is supposed to be considered. Catching the SyntaxError solves this.

```
ast.literal_eval("Don't forget about single quotes")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/anaconda2/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Don't forget about single quotes
                                   ^
SyntaxError: EOL while scanning string literal
```